name: native windows

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: picked_group_fdr_gui
    - name: Install dependencies
      shell: bash -el {0}
      run: |
        mamba install -c conda-forge mokapot pyinstaller
    - name: Collect submodules
      run: |
        mamba run python import_lxml.py
