name: native windows

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - name: download-xml
        run: |
          wget https://proteowizard.sourceforge.io/releases/bt81.xml -O bt81.xml

