name: native windows

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v2
      - name: download-xml
        run: |
          DIR
          set BOOST_ASIO_BASE=boost_asio_1_30_2
          set BOOST_ASIO_URL="https://sourceforge.net/projects/asio/files/asio/1.30.2 (Stable)/%BOOST_ASIO_BASE%.zip/download"
          CALL .github/workflows/download_file_macro.bat "%BOOST_ASIO_URL%" "%~dp0\bt81.xml"
          DIR %~dp0
          EXIT /B



